# Short, Kindergarten-friendly one-line blurbs for each episode, keyed by
# Spotify episode id. These replace the (often adult-toned) Spotify
# description on the dashboard. If a new episode isn't listed here yet,
# parse_episodes.py falls back to its real description and prints the id/title
# so a new line can be added here.

KID_BLURBS = {
    "6WaCNc2Oa0H0W2bBpNPRaS": "Returning a lost treasure to its owner",
    "46Z4TDtj7q0v82BEQ1Ivun": "Choosing judges who are kind and fair",
    "2m7VM9oZi2lKfi91gQUM1W": "Choosing blessings over trouble",
    "7w57OScfKZvnlNjRKaCcCw": "Elijah's rainy adventure!",
    "5aZhgYPCoal9vn0XKCYClw": "Moses begins his big goodbye speech",
    "2Po28DrKr7kc82nfZxgV5P": "Pinchas stands up for what's right",
    "3N8lHwJGWIFXtUaPyetKSG": "Everyone wants more food in the desert",
    "3Zk2HOy1Kl4E84wqmwZeCX": "The night before we got the Torah",
    "4Bw1MVnF8VTYkskQ99O71j": "Best friends Jonathan and David",
    "6mKDWNm9iN25vMXKp0gKMc": "Giving the land a rest, too",
    "0L1lqQatouztRtf1sRHdMk": "The sea splits in two!",
    "4eXbEt08es931nEn9h1JqK": "All about our Jewish holidays",
    "3GtSPepVi9VQoNwjuhfn4e": "Why we don't eat bread on Passover",
    "4W3rtQG1GWijbwChyxhmd6": "The story of the first Passover",
    "2DHLxww6gj9ggiOZBwLG5I": "Fair rules for everyone",
    "0ycwH9E0NjiY5nWzjd94Xu": "The Ten Commandments!",
    "0teA1ZZ1jexBTnZMA0oxnm": "The very first Passover Seder",
    "42xo8T7xtx1HEPu2dyCWgA": "Moses and the burning bush",
    "7gk08TJa0bdvysJefaokVC": "Joseph solves Pharaoh's dream",
    "6zOLNDxMwPiEP9cQRca3hu": "Joseph's colorful coat",
    "0deueX2JINJEKM31izvLCB": "Jacob wrestles all night long",
    "5Z2aWZeTd4MDPxg7CcVqYg": "Jacob and Esau, two different brothers",
    "7J8Lgl5zTr1uwrc79eu2SX": "Abraham argues to save a city",
    "2NWbNeOi2jaJOHJFblGaO2": "Noah, the ark, and the flood",
    "70ys0JsixL4oaqyz6qEplp": "Cain and Abel, the first brothers",
    "091kScy7S7XSJ3kZiNLPfa": "Moses picks Joshua to lead",
    "6KZMZigeKEawiyX33Q0Cxr": "Everyone belongs, even the little guys",
    "5Rf4cWN7XIHepPsvnQg6Ja": "Saying thank you for the harvest",
    "2umjoeYfeRo8e2B0Oz6u1U": "Learning to share with others",
    "5cqs0kOrlwxfp6y1d5M4wy": "Elijah's big drought!",
    "4aYRwGQMpTWgCPjue7QaXD": "Moses begs to see the Promised Land",
    "7qPd1F2Ib8xP9hIB0yWXMV": "Job's story about staying strong",
    "6ErpUICMwrRybEfx9AvXac": "Keeping our promises",
    "6lYwXAzFSY7bC7tBG3L5xg": "Pinchas the brave hero",
    "4ippL8ygCX5fm0sR9U1YzE": "A talking donkey!",
    "4my9TphVDI7RpjhjK5B9Gz": "Saying goodbye to Aaron",
    "4z20z75XMIzNbgAJBDkIrJ": "Korach tries to take over",
    "3Tm3vx3IxWNrh4m99UN19K": "Twelve spies scout the land",
    "2JBGLkaS76pxybGUU0ZPux": "Honi draws a circle and waits",
    "3pyNf5vsk0znQ5eg5YLAFu": "Counting everyone in the camp",
    "6i9A8a87BMd0uGEtMVbQFx": "Resting the land like Shabbat",
    "7xACu387rnsvmGvxWiOtsZ": "A wise rabbi's amazing miracles",
    "6GeXuJSP08IXrHLFzXeGTn": "Being holy and being kind",
    "6UN2jadec7TqM0DPTLY4hK": "Ten brave teachers",
    "5u1TPm0h9GbnrGtst9G3Is": "A tiny letter with a big lesson",
    "4VzMQP2HDVdkwtUzGF13Mb": "Finishing God's special home",
    "6D8682ZHB4T5AmVW5jnXs1": "Everyone helps build the Mishkan",
    "1dJ0TTbMei1AjYXKloRy7g": "Queen Esther saves the day!",
    "4v7P5BQ9Lugpka8mvwR8sB": "Aaron's fancy priest clothes",
    "2X70QHUi9X0tOhaaIWuWe7": "Building God's special tent",
    "7eB36srCpcuqu9pL7bGehP": "New laws for a new nation",
    "6ZpOLnUJSTH0uSJ76PbzHV": "God gives the Ten Commandments",
    "1t3dwzEXDtnnKM1zkQwOs8": "Crossing the Red Sea",
    "2jAc0maXk0C7uirnQrV56q": "Getting ready to leave Egypt",
    "2OIWBE60MaPWEkH8MpwRAL": "The first plagues hit Egypt",
    "3iKR46NKy5qU14X81p6G8h": "Baby Moses grows up in a palace",
    "2LBAF9JmvAssgHIg4o4Exx": "Jacob's last blessing for his family",
    "4QI6rJAKl6fzxlmcei7yRF": "Joseph is thrown in a pit",
    "6wtIysUY493eid6QRPDTBO": "Jacob's dream of a ladder to heaven",
    "4nEKJgY68MOw3fZcZDUS1B": "Finding a wife for Isaac",
    "4JyyRdzeQKEkKELncvPquz": "A tough test for Abraham",
    "0XRUUvMrCXd0cgQT9e3tYk": "Abraham packs up and leaves home",
    "2qbi04KlJMLYWo7IdWtvfY": "Giants before the great flood",
    "7906mCcb4euhLMhCVMSxiC": "Building our sukkah",
    "4SujogTRs9MaieGRKxZqvG": "A special day to say sorry",
    "6aV8LySVBSrwj1CUluqlou": "Moses picks Joshua to lead",
    "768IVH9oc7eaeHhxMsAc4n": "Remembering where we came from",
    "6rwQms1JhcUYCB826L53ia": "Rules for treating others kindly",
    "40UXu1EicNQrnDIy2tlhod": "Choosing peace over fighting",
    "6yKpOqGUqMejEJpF4M3dXD": "Moses says thank you before he goes",
    "74kub5EgdYc245rk23cmIS": "A hopeful story for a sad day",
    "08ZfDHAYpFuRiGh0Fvl8Yl": "Remembering the whole long journey",
    "5UG681VyBT8HuMvZFCcGUW": "Moses' very last task",
    "5ufQoOyFdaGnRgmbAOeK1M": "Counting everyone one more time",
    "20P2l8VUEXUPMRdlTcOKKF": "Bilaam and his talking donkey",
    "2IMO6zdkc6wValHhEI2vwe": "Miriam and Aaron say goodbye",
    "4BMEW5yM3gUw0U9qjPibjw": "A big rebellion in the desert",
    "6ySNy9P58fkbfc56AFfXuY": "Two brave spies and a red rope",
    "5PfKxJoaGgf0iuADawkftK": "Lighting the golden menorah",
    "2hDMtZJsnAkxmMmEYkolXW": "A special blessing for everyone",
    "4SDaampJUX9cUrMcDrcZM9": "Time to count everybody!",
    "1s0rRziC8wKDewXQQ4i5Xj": "Choosing to follow good rules",
    "3Av5ByjYjcUoHoVyIj8IXn": "Letting the land rest, too",
    "3kwTC8WCaevqoMYHbXk931": "The power of kind words",
    "1xtnhqkfvCckCzWcRy0klC": "Being kind to one another",
    "1ibdhorOly7lXtGCXdUux2": "Aaron's big job on Yom Kippur",
    "3l2iPbnkBbOSmp2QVw3Pm2": "Miriam learns about kind words",
    "1gtsoPRZNx0PKlNMHcuPKV": "Taking care of our bodies",
    "0YrUzEoe2YKvBLMpkxGPUc": "King David and the Holy Ark",
    "1FUA91h4SmB9T5aRJ3GTDq": "Aaron becomes a priest!",
    "1LaMcsR10zIGloAGDB4AME": "Aaron learns how to bring offerings",
    "4hw5p0wnkSuedUwabR18BS": "The Mishkan is finally finished!",
    "11F2Q7YP8C2gczxDf7sz7q": "Building the Mishkan together",
    "37seWDnQmyDSXTKVUq1SJc": "Aaron and the Golden Calf",
    "6202KuUyfhrlhsMamkQqTx": "Aaron's fancy priest clothes",
    "4iJr8bSWWESeeII4aFEAfT": "Everyone gives to build the Mishkan",
    "1JcOVHCqulwGTJRUUr4p1D": "Moses learns God's rules",
    "7fCaJ5AcXlV00eVDFDYL24": "Standing together at Mount Sinai",
    "63nyGWNCHK9xOk4lATDDqV": "Singing and dancing after the sea splits",
    "7wqFKk55r1MqOIIMtLUlv7": "The very first Passover Seder",
    "4NoZlGCtWfS18SJ7D2t6Xi": "Frogs, blood, and lice!",
    "259Wd4dwtTR3034dKylUjU": "Baby Moses is saved from the river",
    "5AXDbFgMtUKiUec7AYFsdT": "Jacob's last words to his sons",
    "39k8FDdKnceb55cd39Kt0T": "Joseph tells his brothers who he is",
    "5DqQlLWWNJvXobLRTQQcui": "Joseph becomes Pharaoh's helper",
    "11JPxnjnIgvDBab9sOhk77": "Joseph's brothers get jealous",
    "1RbJUEu5Wn33WynSuBzCq3": "Jacob wrestles a mysterious stranger",
    "1HkDVtO5RtmROQGmLznZDi": "Jacob sneaks away from Laban",
    "3b5CVy98roVtMNVoRt95AE": "Isaac digs wells in a new land",
    "6g8o9rLc9I97hG8bL1Woa1": "Who will lead after Sarah and Abraham?",
    "7vGuo2nw7sdo9tu0AbSqhU": "Abraham welcomes everyone in!",
    "2fkbaZ39pE22aO5c1avzAU": "Young Abraham smashes the idols!",
    "1VUZU9dbwsb1A4QOCHtFam": "Noah builds a big boat",
    "2jqk4PtKEXm5wSsKmrq7Dt": "Dancing with the Torah!",
    "6oEk6BQvO4BNp8fNLtShfD": "Four special plants for Sukkot",
    "6g53XneuA3R8tq7zNTh3QO": "Moses sings his very last song",
    "4HWUxZIGRftMOm1QCHCrZi": "Hannah's prayer from the heart",
    "3AoVapGACTcUCTmhS4Kh5B": "Everyone is part of the promise",
    "43hm6NIvoRXTl4UnhNYDzM": "Bringing the first fruits to say thanks",
    "0WwNK5wAVjFQ3qOKK7QYgj": "A gentle rule about a mother bird",
    "67sVJgSMF8f4joFlnJvcHm": "Judges who are fair and kind",
    "5snOi2b26b1IeFCfS5xq2e": "Sharing what we have with others",
    "70CQUr5PSH4WkxEkCZ7uwH": "Elijah and the big drought",
    "6PlQVjRdh9V4mnTVGevpEV": "Words of comfort after a sad day",
    "6Et8SdNwbPNJzJHOHIr4Jy": "Moses reminds everyone of their story",
    "0AGeoE8enpHDcGwd6q55xH": "Promises really matter",
    "49DTm9NdnRidGwuwSHDaaO": "Pinchas stands up tall",
    "49En2Kak0mzxx6b4RJOR51": "Miriam, Aaron, and a talking donkey",
    "1Rl4J3E9iTiFGtVtWNqNND": "Korach's rebellion against Moses",
    "30Xt1PUTQfJlJeR1T3HafQ": "Twelve spies check out the land",
    "0VelW5oIIFqv4uHVKDfniz": "Everyone wants more food in the desert",
    "2Db5BuveK54a3kRIwnKBZH": "Samson: the strongest hero",
    "4CZslAw006uApPfLDozPFS": "The night before we got the Torah",
    "2LWZIbjPSo1LgzzEeno0iq": "Getting organized for the big journey",
    "0Uk1HVL5mI475MohYTSbtp": "Resting the land like Shabbat",
    "7dGzxCovvrnciEZbCsjrBl": "Celebrating our holidays together",
    "0dlfwdu20m3YonFWQn7D2y": "Aaron's big job and being kind",
    "2epZSNt1aQqyLrvy40JSRP": "Staying healthy in the camp",
    "4ApNFW5Iq6mZcLzvFIYIIB": "The Mishkan opens for the first time",
    "1KcABEjE1utmgVPUjEwaEO": "Getting Aaron ready to be a priest",
    "1OS6nyCDHGoimGMwzJ3uQh": "Getting close to God",
    "3ZEVsZSwnlVZAPanTalaap": "Building God's home together",
    "4tbTdfFeARosnGLQJPhE88": "Aaron and the Golden Calf",
    "37WAR3f3EIBQ2a4PmjIt8z": "Aaron gets his special outfit",
    "0jEDHF9s7PuF83nfJVM9yq": "Time to build the Mishkan!",
    "4zq4NbysHQE4FuEIPWTz4M": "Rules for being kind and fair",
    "4FBqF6Gg0J4EgssXTRG9jc": "The big day at Mount Sinai",
    "4EpoDoYWwAqwCHqXJcPoYf": "The sea splits in two!",
    "0e1p621Ksd0rmK19tcDNWR": "Finally free from Egypt!",
    "43LTckB8yCmSmSzikwtTNH": "The plagues begin!",
    "5nNmmdVFlUb31MxNYIdEaq": "Baby Moses is born and saved",
    "4HWXGeIADkFZiUspEz83Ag": "Jacob and Joseph say goodbye",
    "2Br61KZGDJZz5Q6qckaqvZ": "The brothers learn the truth",
    "5Wfh5HftG3zoK5UsonmUan": "Joseph becomes Pharaoh's right-hand man",
    "27HhGPbEKqMTErylfgnRbe": "Joseph's coat of many colors",
    "1d8UYOlX3GHqk3aUzYXQcC": "Joseph gets thrown in a pit",
    "0DJG4e5Io6nrxlftMn9ASG": "Jacob and Esau finally meet again",
    "69qrVUzQv6pkWM3QtjOzyq": "Jacob's dream of angels on a ladder",
    "0MBjX4obuiCdrmKpJVGZiQ": "Jacob and Esau, twin brothers",
    "0AYwim8sd7O9k3jcBPMcfP": "Finding Rebecca at the well",
    "53zBNPAK5BkainqMyiMbLy": "Three special visitors for Abraham",
    "759qcZqHJaTdhfO9Tf0kTf": "Abraham's big journey begins",
    "6ncg7VZAraPdQWaNbu7Aur": "Noah and the great flood",
    "4VjgIirHZsBYj5OJXoH6zT": "How the world began!",
    "14h6nerJNMigAumzUpJsDg": "Moses blesses the people and says goodbye",
    "6PofijeWZrXvO02H4MxpNz": "Moses' final farewell song",
    "0wajiIRAq6OS0gZWFZb6jy": "Everyone is part of the promise",
    "2fkNd0BWqi8oP4jxrlzO73": "Thanking God for the harvest",
    "7gBFRYZch2Sold4CFrEj2m": "Many little rules for kindness",
    "0EGOlI1IJ34Din6qDZzh9f": "Choosing good judges",
    "1ZfAVF9AYgZ6Jz4AC2U5wZ": "Choosing to do what's right",
    "6uwIUJY2Tv2GV3ID6u1Zxr": "Elijah's rainy adventure",
    "2tESl1FBY16Ew2AUNvRpbp": "Moses begs to see the Promised Land",
    "3XoqWJGZ9I2KHygJ8UYvkp": "Remembering a sad day in history",
    "7wQ23JCL3WJkjZbigCmBX1": "Looking back on the long journey",
    "0U42BDBXLAIdjlSdf7QU7B": "Pinchas the peacemaker",
    "4GT38RWDGAFfO1jMXscDjl": "The prophet with the talking donkey",
    "40e9ToSmWwKB79rC4yVLJf": "A sad goodbye in the desert",
    "4zjs6FDQIhIMfOAG0vnMon": "Korach challenges Moses",
    "2mJ7KR6c5zQtwUPP0MRZTi": "Spies scout the Promised Land",
    "5fRpK48CmL9gCkSYfc29bd": "Yummy dairy treats for Shavuot",
    "2QLU1cOYbMQ8cdmrM8qYUz": "Yummy Passover food questions",
    "7gCXYlFEZPsVJuflg9Yw97": "Esther's secret plan",
    "44qSjHvOjNJ5QfIMmpZ1IV": "The sea splits in two!",
    "6y9t9Gi3QoNOmJfWAifMoL": "Hail falls on Egypt",
    "3u6czY3kpGmzFpYFCxHSbE": "Why we light the menorah",
    "0a44zn2ZasHifFfxt24E3U": "Spin the dreidel!",
    "6346b99ou86sggjDckweLZ": "Yummy oily Hanukkah treats",
    "7jyH1LurT6vRW9k60HSPww": "All about the etrog",
    "6MGsY40khaOEdaRISQyNoU": "Why the shofar sounds that way",
    "2mArnNRS9ochwyOD6ULR3V": "Their clothes never wore out in the desert!",
}
